version: '3'

services:
  db:
    container_name: Todo-DB
    environment:
      - POSTGRES_DB=Todo
      - POSTGRES_USER=TodoLogin
      - POSTGRES_PASSWORD=SeCrEtSECRETsecret
    image: postgres:15-bookworm
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  
  api:
    build: ./todo_api
    container_name: Todo-API
    depends_on:
      - db
    image: kidsdb-api
    restart: on-failure
    volumes:
      - ./todo_api/logs:/app/logs
      - ./todo_api/media:/app/media
      - ./todo_api/static:/app/static
  
  webui:
    build: ./todo_webui
    container_name: Todo-WEBUI
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV:-local}
    image: kidsdb-webui
    restart: on-failure
    volumes:
      - ./todo_webui/.next:/app/.next

  proxy:
    container_name: Todo-PROXY
    depends_on:
      - webui
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    volumes:
      - ./certs:/etc/ssl/certs
      - ./todo_api/media:/media
      - ./todo_api/static:/static
      - ./todo_webui/.next:/.next
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
